config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip:[:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  # 顧客用
  # URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  namespace :admin do
    resources :users, only: [:index, :show, :update]
    resources :cosme_categorys, only: [:index, :create, :update]
    get 'homes/top'
  end
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  scope module: :public do
    root to: 'homes#top'
    get '/home/about' => 'homes#about', as: 'about'
    resources :users, only: [:show, :edit, :index, :update, :destroy] do
      resources :bookmarks, only: [:index]
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :cosme_items, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :cosme_comments, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
    end
    get "search" => "searches#search"
    get '/cosme_item/hashtag/:name' => 'cosme_items#hashtag'
    # get '/cosme_item/hashtag' => 'cosme_items#hashtag'
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login_id]
  
  has_one_attached :profile_image
  has_many :cosme_items, dependent: :destroy
  has_many :cosme_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :nickname, presence: true
  validates :login_id, presence: true
         
  def self.guest
    find_or_create_by!(login_id: 'guestuser' ,email: 'guest@example.com', last_name: 'guest', first_name: 'user', nickname: 'guest') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.login_id = "guestuser"
    end
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  
  def self.looks(word)
    if word.present?
      @user = User.where("nickname LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:is_banned)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to cosme_items_path(), notice: 'ゲストでログインしました。'
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">
  <h4>会員一覧</h4>
  <div class="row">
    <div class="col-lg-8 col-md-10 col-sm-12 text-enter">
      <table class="table table-bordered bg-light">
        <tr>
          <th>会員ID</th>
          <th>名前</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
          <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td>
            <%= link_to admin_user_path(user) do %>
              <%= user.last_name %><%= user.first_name %>
            <% end %>
          </td>
          <td><%= user.email %></td>
          <td>
            <% if user.is_banned == false %>
              <p class="text-success">有効</p>
            <% else %>
              <p class="text-secondary">利用停止中</p>
            <% end %>
          </td>
        </tr>
          <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class='container'>
  <div class="row">
    <div class="col-md-4 col-lg-6">
      <div>
        <span class="text-name px-2"><%= @user.last_name %><%= @user.first_name %></span>様の情報
      </div>

      <table class="table table-bordered bg-light">
        <tr>
          <th>会員ID</th>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <th>名前</th>
          <td><%= @user.last_name %><%= @user.first_name %></td>
        </tr>
        <tr>
          <th>ニックネーム</th>
          <td><%= @user.nickname %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th>ステータス</th>
        <td>
          <%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>
          <%= f.radio_button :is_banned, true %>
          <%= f.label :is_banned, "利用停止中", value: true %>
          <%= f.radio_button :is_banned, false %>
          <%= f.label :is_banned, "有効", value: false %>
            <%= f.submit '変更', class:'btn btn-secondary btn-sm', "data-confirm" => "本当に変更しますか？"  %>
          <% end %>
        </td>
      </tr>
    </table>
    <%= link_to '戻る', admin_users_path, class:'btn btn-secondary' %>
  </div>
</div>