config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip:[:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  # 顧客用
  # URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  namespace :admin do
    resources :users, only: [:index, :show, :update]
    resources :cosme_categorys, only: [:index, :create, :update]
    get 'homes/top'
  end
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  scope module: :public do
    root to: 'homes#top'
    get '/home/about' => 'homes#about', as: 'about'
    resources :users, only: [:show, :edit, :index, :update, :destroy] do
      resources :bookmarks, only: [:index]
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :cosme_items, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :cosme_comments, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
    end
    get "search" => "searches#search"
    get '/cosme_item/hashtag/:name' => 'cosme_items#hashtag'
    # get '/cosme_item/hashtag' => 'cosme_items#hashtag'
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="footer fixed-bottom">
  <div class='container'>
  	<div class='row'>
    	<div class='mx-auto text-secondary text-center'>
    		<p>cosme cafe</p>
    		<div>
      		<i class="fab fa-twitter-square"></i>
      		<i class="fab fa-instagram-square"></i>
      		<i class="fab fa-facebook-square"></i>
    		</div>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">cosme cafe</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? && current_user.login_id == 'guestuser' %>
          <li class="navbar-item">
            <%= link_to 'ABOUT', about_path(), class: 'nav-link text-secondary' %>
          </li>
          <li class="navbar-item">
            <%= link_to '投稿一覧', cosme_items_path(), class: 'nav-link text-secondary' %>
          </li>
          <li class="navbar-item">
            <%= link_to 'ログアウト', destroy_user_session_path(), method: :delete, class: 'nav-link text-secondary' %>
          </li>
          <li class="form-inline my-2 my-lg-0">
          <%= form_with url: search_path, local: true, method: :get do |f| %>
            <%= f.select :range, options_for_select([['会員'], ['キーワード']]), {}, class: "form-control" %>
            <%= f.text_field :word, type: "text", placeholder: "Search", class: "form-control mr-sm-2" %>
            <button class="btn btn-secondary" type="submit"><i class="fas fa-search"></i></button>
          <% end %>
          </li>
        <% elsif admin_signed_in? %>
          <li class="navbar-item">
            <%= link_to 'ログアウト', destroy_admin_session_path(), method: :delete, class: 'nav-link text-secondary' %>
          </li>
        <% elsif user_signed_in? %>
          <li class="navbar-item">
            <%= link_to 'マイページ', user_path(current_user), class: 'nav-link text-secondary' %>
          </li>
          <li class="navbar-item">
            <%= link_to '投稿一覧', cosme_items_path(), class: 'nav-link text-secondary' %>
          </li>
          <li class="navbar-item">
            <%= link_to 'ログアウト', destroy_user_session_path(), method: :delete, class: 'nav-link text-secondary' %>
          </li>
          <li class="form-inline my-2 my-lg-0">
          <%= form_with url: search_path, local: true, method: :get do |f| %>
            <%= f.select :range, options_for_select([['会員'], ['キーワード']]), {}, class: "form-control" %>
            <%= f.text_field :word, type: "text", placeholder: "Search", class: "form-control mr-sm-2" %>
            <button class="btn btn-secondary btn-sm" type="submit"><i class="fas fa-search"></i></button>
          <% end %>
           </li>
        <% else %>
          <li class="navbar-item">
            <%= link_to 'ABOUT', about_path, class: 'nav-link text-secondary' %>
          </li>
          <li class="navbar-item">
            <%= link_to 'ログイン', new_user_session_path(), class: 'nav-link text-secondary' %>
          </li>
          
          <li class="navbar-item">
            <%= link_to '新規登録', new_user_registration_path(), class: 'nav-link text-secondary' %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cosmecafe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=M+PLUS+Rounded+1c:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=M+PLUS+Rounded+1c:wght@700&family=Yusei+Magic&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=M+PLUS+Rounded+1c:wght@700&family=Solitreo&family=Yusei+Magic&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@700&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div style='height:60px' >
    </div>
    <main>
      <p id="notice"></p>
    <%= yield %>
    </main>
     <div style='height:60px' >
     <%= render 'layouts/footer' %>
  </body>
</html>